"""The launchd jobs.

D-035: every plist carried its own copy of the LMS_* paths, under a comment
admitting "they are not linked". They drifted, and it cost a backup — the
nightly job wrote to one restic repository while the restore test verified
another, both reporting success indefinitely.

It then happened a SECOND time, in the file that had the warning written in it.
com.lms.watchfolder.plist declared the iCloud inbox, which is right, while
lms.env declared ~/LMS/inbox, which is an empty directory nothing has ever
written to. The scheduled job looked in the right place and anything run from a
shell looked at nothing, found nothing, and reported no error at all.

Writing the lesson down twice did not stop it happening twice. So it is a test.
"""

import plistlib
import re
from pathlib import Path

import pytest

OPS = Path(__file__).resolve().parents[1] / "ops"
REPO = Path(__file__).resolve().parents[2]

PLISTS = sorted(OPS.glob("*.plist"))


def load(path: Path) -> dict:
    return plistlib.loads(path.read_bytes())


def test_there_are_plists_to_check():
    """Guards every test below from passing vacuously."""
    assert PLISTS, "no plists found — these tests would all pass on nothing"


@pytest.mark.parametrize("path", PLISTS, ids=lambda p: p.name)
def test_the_plist_is_well_formed_xml(path):
    """launchd refuses to load a malformed plist, and the symptom is a job
    that silently never runs — no error, nothing in the log, because the log
    is configured inside the file it could not read."""
    try:
        load(path)
    except Exception as exc:
        pytest.fail(f"{path.name} is not loadable: {exc}")


@pytest.mark.parametrize("path", PLISTS, ids=lambda p: p.name)
def test_no_comment_contains_a_double_hyphen(path):
    """`--days 2` inside an XML comment makes the whole file unparseable.

    These plists carry long comments explaining why each choice was made, and
    command-line flags are exactly what such a comment wants to quote. Caught
    once already, on com.lms.mail.plist, before it ever reached the Mac. The
    generic parse error above says "invalid token, line 25"; this says what is
    actually wrong.
    """
    text = path.read_text(encoding="utf-8")
    for comment in re.findall(r"<!--(.*?)-->", text, re.S):
        assert "--" not in comment, (
            f"{path.name} has a comment containing '--', which is illegal in "
            f"XML. launchd will refuse the file and the job will never run. "
            f"Rephrase rather than quoting the flag.")


@pytest.mark.parametrize("path", PLISTS, ids=lambda p: p.name)
def test_no_plist_declares_an_lms_path(path):
    """The rule D-035 bought, and the one that was already written down.

    lms.env is generated by bringup_mac.sh from the volume layout, so it is the
    only description of these paths that is derived rather than retyped. A
    plist that names one is a second source, and a second source drifts.

    Plists carry only what launchd cannot supply any other way: PATH, TZ,
    PYTHONUNBUFFERED.
    """
    env = load(path).get("EnvironmentVariables", {})
    declared = sorted(k for k in env if k.startswith("LMS_"))
    assert not declared, (
        f"{path.name} declares {declared}. ops/lms.env is the single source "
        f"for these; have the entry script call load_lms_env() instead. This "
        f"is D-035, and the second occurrence was in a file that already "
        f"carried the warning.")


@pytest.mark.parametrize("path", PLISTS, ids=lambda p: p.name)
def test_the_interpreter_is_named_absolutely(path):
    """`python3` in a plist resolves to Apple's 3.9 in /usr/bin, because
    launchd inherits no login PATH. The failure is an ImportError in a log
    nobody reads."""
    argv = load(path)["ProgramArguments"]
    exe = argv[0]
    assert exe.startswith("/"), f"{path.name} runs {exe!r} off PATH"
    assert ".venv/bin/python" in exe, (
        f"{path.name} runs {exe!r}, not the project venv")


@pytest.mark.parametrize("path", PLISTS, ids=lambda p: p.name)
def test_every_script_a_plist_runs_exists(path):
    """A plist pointing at a renamed script fails at 02:30 and nowhere else.

    Checked against the repo by basename rather than the absolute /Users/mleca
    path, since the development machine is not the Mac.
    """
    argv = load(path)["ProgramArguments"]
    for arg in argv[1:]:
        if arg.endswith(".py"):
            assert (OPS / Path(arg).name).exists(), (
                f"{path.name} runs {arg}, which is not in ops/")
        elif arg == "-m":
            pytest.fail(
                f"{path.name} runs a module directly. Entry points live in "
                f"ops/ so they can load lms.env — see ops/watch.py")


@pytest.mark.parametrize("path", PLISTS, ids=lambda p: p.name)
def test_no_plist_contains_a_secret(path):
    """A plist is world-readable and lands in git (spec §12.4).

    Credentials come from the Keychain at run time, never from here.
    """
    # Only the parsed dict is searched, not the file text: the words appear in
    # the comments explaining why they are absent, and a test that failed on
    # its own documentation would teach people to delete the documentation.
    text = path.read_text(encoding="utf-8").lower()
    env = load(path).get("EnvironmentVariables", {})
    for key, value in env.items():
        k = key.lower()
        assert not any(w in k for w in
                       ("password", "passphrase", "secret", "token", "key")), (
            f"{path.name} sets {key} in the environment")
    assert "restic_password" not in text


@pytest.mark.parametrize("path", PLISTS, ids=lambda p: p.name)
def test_the_label_matches_the_filename(path):
    """`launchctl bootout gui/501/com.lms.mail` uses the label. A file called
    com.lms.mail.plist that declares a different one is a job you cannot stop
    by guessing."""
    assert load(path)["Label"] == path.stem


@pytest.mark.parametrize("path", PLISTS, ids=lambda p: p.name)
def test_a_scheduled_job_does_not_also_keep_alive(path):
    """KeepAlive on a one-shot restarts it in a loop forever."""
    p = load(path)
    if "StartCalendarInterval" in p:
        assert not p.get("KeepAlive"), (
            f"{path.name} is scheduled AND KeepAlive — it will run "
            f"continuously, not on the schedule")


@pytest.mark.parametrize("path", PLISTS, ids=lambda p: p.name)
def test_output_is_captured(path):
    """A job whose stdout goes nowhere is a job that fails invisibly."""
    p = load(path)
    assert p.get("StandardOutPath") and p.get("StandardErrorPath"), (
        f"{path.name} discards its output")


def test_the_mail_poll_window_overlaps_itself():
    """--days 2, not 1.

    Re-reading yesterday is free — identity is the sha256 of the rendered
    message, so the second sighting files nothing. The overlap is what makes a
    missed run harmless: if the Mac is asleep at 07:00 the next run still
    catches the mail, with no repair script and no stored cursor to lose.
    """
    mail = OPS / "com.lms.mail.plist"
    if not mail.exists():
        pytest.skip("no mail plist")
    argv = load(mail)["ProgramArguments"]
    assert "--days" in argv
    days = int(argv[argv.index("--days") + 1])
    assert days >= 2, (
        "a one-day window with a daily schedule loses a day's mail whenever a "
        "run is missed")


def test_lms_env_is_never_committed():
    """It is generated per machine and chmod 600. A committed one would
    overwrite the real paths on pull with whatever the last author had."""
    gitignore = (REPO / ".gitignore").read_text(encoding="utf-8")
    assert re.search(r"^\s*(lms/)?ops/lms\.env\s*$", gitignore, re.M), (
        "ops/lms.env is not gitignored")
