"""Load ops/lms.env so a script and its launchd job agree about the paths.

WHY THIS EXISTS
---------------
Every plist carried its own copy of the LMS_* variables, with a comment
admitting the hazard: "Mirrors ops/lms.env ... they are not linked." They
drifted, and it cost a backup.

`lms.env` had no LMS_BACKUP_REPO at all, so an interactive run fell through to
the code default:

    /Volumes/MacStudioHD/LMS/LMS_backup      <- ./ops/backup.py, ./ops/restore_test.py

while com.lms.backup.plist declared:

    /Volumes/MacStudioHD/LMS_backup          <- the nightly job

Two restic repositories. The scheduled backup wrote to one; the restore test
verified the other. Both reported success, indefinitely, and the failure would
have surfaced on the morning someone needed a snapshot that was never in the
repository they were looking at.

lms.env is generated by bringup_mac.sh from the volume layout, so it is the
only description of the paths that is derived rather than retyped. Scripts
read it; plists carry only what launchd cannot get any other way — PATH, TZ,
and PYTHONUNBUFFERED.

Existing environment variables always win. An operator running
`LMS_BACKUP_REPO=/Volumes/Other ./ops/backup.py` means it, and a loader that
overrode them would be its own kind of surprise.
"""

from __future__ import annotations

import os
import re
from pathlib import Path

# `export KEY="value"` / `export KEY=value` — the shape bringup_mac.sh writes.
# Deliberately not a shell invocation: sourcing a file to read four paths
# would run whatever is in it, and this is called by a job that runs
# unattended at 02:30.
_LINE = re.compile(r'^\s*export\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$')


def load_lms_env(path: Path | None = None, *, override: bool = False) -> dict[str, str]:
    """Read ops/lms.env into os.environ. Returns what it set.

    Missing file is not an error: a developer machine has no lms.env and the
    code defaults are correct there.
    """
    path = Path(path) if path else Path(__file__).resolve().parent / "lms.env"
    applied: dict[str, str] = {}
    if not path.exists():
        return applied

    for raw in path.read_text(encoding="utf-8").splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        m = _LINE.match(raw)
        if not m:
            continue
        key, value = m.group(1), m.group(2)
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        if override or key not in os.environ:
            os.environ[key] = value
            applied[key] = value
    return applied
