#!/usr/bin/env bash
#
# Day 1-2 bring-up on the Mac Studio.
#
# Run this ON THE MAC, from the repo checkout, as Matthew's user (D-009).
# It is idempotent: safe to re-run after a failure or a reboot.
#
# It does NOT touch credentials, mailboxes, or the network. It creates the
# storage trees, installs the two Python dependencies, and runs the test
# suite so you know the code works on the machine it will actually live on
# rather than on the workstation it was written on.
#
# Usage:
#   ./ops/bringup_mac.sh /Volumes/Vault
#
# The argument is the RAID volume that will hold the filed trees (C5).
# Pick an ENCRYPTED volume. If you are unsure which are encrypted, run:
#   diskutil apfs list | grep -A2 -i "FileVault"

set -euo pipefail

RAID_ROOT="${1:-}"
if [[ -z "$RAID_ROOT" ]]; then
  echo "usage: $0 /Volumes/<volume>   # the RAID volume for LMS data (C5)" >&2
  exit 2
fi
if [[ ! -d "$RAID_ROOT" ]]; then
  echo "error: $RAID_ROOT is not mounted" >&2
  exit 1
fi

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

echo "==> repo:  $REPO_DIR"
echo "==> RAID:  $RAID_ROOT"

# ---------------------------------------------------------------------------
# 1. Encryption check. Warn loudly, do not silently proceed.
# ---------------------------------------------------------------------------
echo
echo "==> Checking encryption on $RAID_ROOT"
if diskutil info "$RAID_ROOT" 2>/dev/null | grep -qi "FileVault:.*Yes"; then
  echo "    encrypted: yes"
else
  echo "    *** WARNING: $RAID_ROOT does not report FileVault encryption. ***"
  echo "    C5/D-011 requires every volume holding LMS documents to be encrypted."
  echo "    Encrypt in place with:  diskutil apfs encryptVolume $RAID_ROOT -user disk"
  echo "    Save the passphrase to the SYSTEM keychain so it mounts after a"
  echo "    FileVault unlock without a second prompt."
  read -r -p "    Continue anyway? [y/N] " reply
  [[ "$reply" == "y" || "$reply" == "Y" ]] || exit 1
fi

# ---------------------------------------------------------------------------
# 2. Storage roots (BUILD_PLAYBOOK Day 1 step 6)
# ---------------------------------------------------------------------------
echo
echo "==> Creating storage roots"
ARCHIVE="$RAID_ROOT/LMS/archive"
ORIGINALS="$RAID_ROOT/LMS/_originals"
QUARANTINE="$HOME/LMS/quarantine"
INBOX="$HOME/LMS/inbox"

# Tree names must match entities.yaml `tree:` values exactly.
for tree in PERSONAL/Matthew PERSONAL/Jesse PERSONAL/Mother PERSONAL/Father \
            PERSONAL/Household MRECAI CHSHINK ATLASE MLECA _UNASSIGNED _JUNK; do
  mkdir -p "$ARCHIVE/$tree"
done
mkdir -p "$ORIGINALS" "$QUARANTINE" "$INBOX"

# The originals store is the only copy that is never rewritten. Lock it down.
chmod 700 "$ORIGINALS"

echo "    archive:    $ARCHIVE"
echo "    originals:  $ORIGINALS"
echo "    quarantine: $QUARANTINE"

# ---------------------------------------------------------------------------
# 3. Python dependencies
# ---------------------------------------------------------------------------
echo
echo "==> Python"
command -v python3 >/dev/null || { echo "python3 missing: brew install python@3.12" >&2; exit 1; }
python3 --version
python3 -m pip install --quiet --user pyyaml pytest

# ---------------------------------------------------------------------------
# 4. Environment. Written to a file the LaunchAgent sources.
#    NOT a .env with secrets in it — these are paths only. Credentials live
#    in the Keychain (D-016) and never in a file.
# ---------------------------------------------------------------------------
echo
echo "==> Writing ops/lms.env (paths only, no secrets)"
cat > "$REPO_DIR/ops/lms.env" <<EOF
# Generated by bringup_mac.sh. Paths only — never put a credential here.
export LMS_ARCHIVE_ROOT="$ARCHIVE"
export LMS_ORIGINALS_ROOT="$ORIGINALS"
export LMS_QUARANTINE_ROOT="$QUARANTINE"
export LMS_INBOX="$INBOX"
export LMS_DB="$ARCHIVE/../lms.db"
export TZ="America/New_York"
EOF
chmod 600 "$REPO_DIR/ops/lms.env"

# ---------------------------------------------------------------------------
# 5. Verify on the real machine
# ---------------------------------------------------------------------------
echo
echo "==> Running the test suite on this Mac"
# shellcheck disable=SC1090
source "$REPO_DIR/ops/lms.env"
python3 -m pytest || { echo "TESTS FAILED — stop here, do not proceed to Day 3." >&2; exit 1; }

# ---------------------------------------------------------------------------
# 6. Report what is still blocked
# ---------------------------------------------------------------------------
echo
echo "==> Outstanding client items"
python3 - <<'PY'
import sys
sys.path.insert(0, ".")
from core.pipeline.registry import load_registry
r = load_registry()
missing = r.placeholders()
if missing:
    print(f"    C16 UNANSWERED for: {', '.join(missing)}")
    print("    Documents for these entities will file, but with placeholder")
    print("    legal names. Fill config/entities.yaml before real mail flows.")
else:
    print("    C16 complete — no placeholders remain.")
PY

cat <<'EOF'

==> Done. Day 1-2 is live on this machine.

Still blocked, in priority order:
  C16  legal names, EINs, name variants        -> classifier accuracy
  D-017 rotate the seven exposed credentials   -> before ANY mailbox connects
  D-017 replace the OpenClaw account password  -> it is currently 123456
  C21  identify the rescueadmin account        -> before Phase 8 hardening
  C11  Workspace admin + 4 Shared Drives       -> Day 3
  C5   written approval to encrypt in place    -> if the warning above fired

Next: Phase 6 (OpenClaw config) and Phase 7 (Telegram), then Day 3 email.
EOF
